import type { Survey, Question, QuestionOption } from "./types"
import { PERSONA_DETAILS } from "./persona-details.generated"

// 옵션 헬퍼: 라벨 배열 -> {id,label}[] (id는 문항 내에서만 고유하면 됨)
const o = (labels: string[]): QuestionOption[] => labels.map((label, i) => ({ id: `o${i}`, label }))

const LIKERT = ["전혀 아니다", "아니다", "보통이다", "그렇다", "매우 그렇다"]

// ---------------------------------------------------------------------------
// Part A — 성향 진단 (40문항, 채점됨)
// ---------------------------------------------------------------------------
type ARow = [id: string, text: string, axisId: string, direction: "forward" | "reverse"]

const partAPersonality: ARow[] = [
  ["A1", "낯선 사람과도 금방 친해지는 편이다", "social", "forward"],
  ["A2", "여러 사람과 함께 있을 때 오히려 에너지가 생긴다", "social", "forward"],
  ["A3", "혼자만의 시간이 있어야 재충전이 된다", "social", "reverse"],
  ["A4", "새로운 모임에 나가는 것이 부담스럽지 않다", "social", "forward"],
  ["A5", "모르는 사람이 많은 자리에서도 금방 편안해진다", "social", "forward"],
  ["A6", "새로운 경험 자체가 스트레스보다 즐거움에 가깝다", "adventure", "forward"],
  ["A7", "처음 해보는 액티비티에도 망설임이 적다", "adventure", "forward"],
  ["A8", "일정은 미리 정해두지 않으면 불안하다", "flow", "reverse"],
  ["A9", "그때그때 기분에 따라 계획을 바꾸는 편이다", "flow", "forward"],
  ["A10", "할 일 목록(체크리스트)이 있어야 마음이 놓인다", "flow", "reverse"],
  ["A11", "예상치 못한 변수가 생겨도 오히려 재미있다", "flow", "forward"],
  ["A12", "목적지에 대한 최소한의 정보(리뷰, 지도)는 꼭 확인해야 마음이 놓인다", "flow", "reverse"],
]

const partATravel: ARow[] = [
  ["B1", "여행지에서는 사람 많고 활기찬 곳에 가야 여행 온 기분이 난다", "social", "forward"],
  ["B2", "여행 중 만난 사람과 이후에도 연락을 이어가곤 한다", "social", "forward"],
  ["B3", "가본 적 없는 곳이 가본 곳보다 더 끌린다", "adventure", "forward"],
  ["B4", "계획에 없던 곳이라도 흥미로우면 바로 들어가 본다", "adventure", "forward"],
  ["B5", "유명한 관광지보다 이름 없는 골목이 더 궁금하다", "adventure", "forward"],
  ["B6", "여행 경비는 꼭 필요한 곳에만 계획적으로 쓰는 편이다", "experience", "reverse"],
  ["B7", "특별한 경험이라면 사진과 기록에 남는 지출은 아끼지 않는다", "experience", "forward"],
  ["B8", "여행 가기 전에 맛집과 동선을 미리 예약·정리해두는 편이다", "flow", "reverse"],
  ["B9", "그날그날 발길 닿는 대로 다니는 게 좋다", "flow", "forward"],
  ["B10", "대기 시간이 있으면 보통 다른 곳을 찾아본다", "flow", "reverse"],
  ["B11", "매일 저녁 다음 날 일정을 미리 정리해두는 편이다", "flow", "reverse"],
  ["B12", "예정된 시간보다 조금 늦어져도 크게 개의치 않는다", "flow", "forward"],
]

const partAFood: ARow[] = [
  ["C1", "여행지에서도 평소 먹던 익숙한 메뉴를 고르는 편이다", "adventure", "reverse"],
  ["C2", "그 지역이 아니면 못 먹는 특이한 음식에 도전해보고 싶다", "adventure", "forward"],
  ["C3", "메뉴판에 낯선 음식이 있으면 오히려 호기심이 생긴다", "adventure", "forward"],
  ["C4", "무엇을 먹을지 실패하고 싶지 않아서 검증된 메뉴를 고른다", "adventure", "reverse"],
  ["C5", "향신료가 강하거나 독특한 향의 음식도 일단 시도해본다", "adventure", "forward"],
  ["C6", "여행 중 식사는 가성비가 가장 중요하다", "experience", "reverse"],
  ["C7", "특별한 날인 만큼 가격보다 분위기·경험을 우선한다", "experience", "forward"],
  ["C8", "웨이팅이 길어도 유명한 곳이면 기다릴 가치가 있다고 생각한다", "experience", "forward"],
  ["C9", "유명 맛집이라도 가격이 과하다 싶으면 가지 않는다", "experience", "reverse"],
]

const partALodging: ARow[] = [
  ["D1", "숙소에서 다른 여행자들과 어울리는 것도 여행의 재미다", "social", "forward"],
  ["D2", "숙소는 무조건 조용하고 프라이빗해야 쉬는 것 같다", "social", "reverse"],
  ["D3", "도미토리나 다인실보다 개인실이 훨씬 편하다", "social", "reverse"],
  ["D4", "숙소는 잠만 잘 수 있으면 충분하다", "experience", "reverse"],
  ["D5", "숙소 자체가 여행의 특별한 기억이 되길 바란다", "experience", "forward"],
  ["D6", "가격이 조금 비싸도 뷰나 분위기가 좋은 곳을 택한다", "experience", "forward"],
  ["D7", "하루 숙박비가 그날 하루 식비 전체보다 비싸도 괜찮다", "experience", "forward"],
]

const makeLikert = (rows: ARow[], sectionId: string): Question[] =>
  rows.map(([id, text, axisId, direction]) => ({
    id,
    part: "A" as const,
    sectionId,
    text,
    type: "likert" as const,
    required: true,
    axisId,
    direction,
    points: 5,
    scaleLabels: LIKERT,
  }))

// ---------------------------------------------------------------------------
// Part B — 여행 취향 프로필 (46문항, 원값 저장)
// ---------------------------------------------------------------------------
const FOOD_CATS = [
  "한식",
  "중식",
  "일식",
  "양식",
  "동남아음식",
  "인도음식",
  "중동음식",
  "멕시코·남미음식",
  "카페/디저트",
  "술집/포차",
  "채식/비건",
  "해산물전문",
]

const partB: Question[] = [
  // B-1 음식 (14)
  {
    id: "B1-1",
    part: "B",
    sectionId: "b-food",
    text: "가장 선호하는 음식 카테고리는? (최대 5개)",
    type: "multi",
    required: true,
    maxSelect: 5,
    options: o(FOOD_CATS),
  },
  {
    id: "B1-2",
    part: "B",
    sectionId: "b-food",
    text: "그중 가장 자신 있게 좋아하는 카테고리 1개는?",
    type: "single",
    options: o(FOOD_CATS),
  },
  {
    id: "B1-3",
    part: "B",
    sectionId: "b-food",
    text: "잘 안 먹거나 피하는 음식 카테고리가 있나요?",
    type: "multi",
    options: o(FOOD_CATS),
  },
  {
    id: "B1-4",
    part: "B",
    sectionId: "b-food",
    text: "식품 알레르기가 있나요?",
    type: "multi",
    required: true,
    allowCustom: true,
    helpText: "안전과 직결되는 항목이에요. 없으면 '없음'을 선택하세요.",
    options: o([
      "없음",
      "난류",
      "우유",
      "메밀",
      "땅콩",
      "대두",
      "밀",
      "고등어",
      "게",
      "새우",
      "돼지고기",
      "복숭아",
      "토마토",
      "아황산류",
      "호두",
      "닭고기",
      "쇠고기",
      "오징어",
      "조개류(굴·전복·홍합 등)",
      "잣",
    ]),
  },
  {
    id: "B1-5",
    part: "B",
    sectionId: "b-food",
    text: "종교·신념에 따른 식단 제약이 있나요?",
    type: "single",
    allowCustom: true,
    options: o(["없음", "할랄", "코셔", "힌두교(소고기 제외)", "락토오보 채식", "락토 채식", "비건"]),
  },
  {
    id: "B1-6",
    part: "B",
    sectionId: "b-food",
    text: "매운맛 선호도는?",
    type: "scale",
    required: true,
    points: 5,
    lowLabel: "전혀 못 먹음",
    highLabel: "아주 잘 먹음",
  },
  {
    id: "B1-7",
    part: "B",
    sectionId: "b-food",
    text: "평소 술을 마시나요?",
    type: "single",
    options: o(["안 마심", "가볍게", "즐겨 마심"]),
  },
  {
    id: "B1-8",
    part: "B",
    sectionId: "b-food",
    text: "여행 중 양조장·와이너리·전통주 체험에 관심 있나요?",
    type: "single",
    options: o(["관심 있음", "상관없음", "관심 없음"]),
  },
  {
    id: "B1-9",
    part: "B",
    sectionId: "b-food",
    text: "날음식(회, 육회, 반숙 등) 섭취가 가능한가요?",
    type: "single",
    required: true,
    options: o(["잘 먹음", "괜찮음", "피함"]),
  },
  {
    id: "B1-10",
    part: "B",
    sectionId: "b-food",
    text: "특별히 꺼리는 식감·재료가 있나요?",
    type: "multi",
    allowCustom: true,
    options: o(["내장류", "물컹한 식감", "뼈 있는 생선", "과도한 기름기"]),
  },
  {
    id: "B1-11",
    part: "B",
    sectionId: "b-food",
    text: "평소 식사 패턴은?",
    type: "single",
    options: o(["아침 꼭 챙김", "아침 거의 안 먹음", "브런치 선호", "야식파"]),
  },
  {
    id: "B1-12",
    part: "B",
    sectionId: "b-food",
    text: "혼자 밥 먹는 것, 괜찮은가요?",
    type: "single",
    options: o(["전혀 상관없음", "가능은 함", "혼자는 불편함"]),
  },
  {
    id: "B1-13",
    part: "B",
    sectionId: "b-food",
    text: "로컬 개인 식당과 익숙한 프랜차이즈, 어느 쪽에 더 끌리나요?",
    type: "scale",
    points: 5,
    lowLabel: "로컬 개인식당",
    highLabel: "익숙한 프랜차이즈",
  },
  {
    id: "B1-14",
    part: "B",
    sectionId: "b-food",
    text: "평소 한 끼 식사에 보통 쓰는 금액은?",
    type: "single",
    options: o(["1만원 이하", "1~2만원", "2~4만원", "4~7만원", "7만원 이상"]),
  },

  // B-2 숙소 (10)
  {
    id: "B2-1",
    part: "B",
    sectionId: "b-lodging",
    text: "선호하는 숙소 유형은? (최대 3개, 우선순위 순으로)",
    type: "multi",
    required: true,
    maxSelect: 3,
    options: o(["호텔", "리조트/풀빌라", "게스트하우스/호스텔", "한옥 등 전통숙소", "독채 펜션", "캠핑/글램핑", "공유숙박(에어비앤비 등)"]),
  },
  {
    id: "B2-2",
    part: "B",
    sectionId: "b-lodging",
    text: "선호하는 객실 타입은?",
    type: "single",
    options: o(["침대형", "온돌형", "상관없음"]),
  },
  {
    id: "B2-3",
    part: "B",
    sectionId: "b-lodging",
    text: "숙소에 꼭 있어야 하는 시설은?",
    type: "multi",
    required: true,
    options: o(["수영장", "조식 포함", "온천/스파", "헬스장", "주차", "반려동물 동반 가능", "무장애(휠체어) 접근", "키친/조리시설"]),
  },
  {
    id: "B2-4",
    part: "B",
    sectionId: "b-lodging",
    text: "흡연 관련 선호는?",
    type: "single",
    required: true,
    options: o(["비흡연자·금연룸 필수", "흡연 가능한 곳 선호", "상관없음"]),
  },
  {
    id: "B2-5",
    part: "B",
    sectionId: "b-lodging",
    text: "숙소 소음에 얼마나 민감한가요?",
    type: "scale",
    points: 5,
    lowLabel: "전혀 민감하지 않음",
    highLabel: "매우 민감함",
  },
  {
    id: "B2-6",
    part: "B",
    sectionId: "b-lodging",
    text: "선호하는 뷰가 있나요?",
    type: "multi",
    options: o(["오션뷰", "마운틴뷰", "시티뷰", "특별히 상관없음"]),
  },
  {
    id: "B2-7",
    part: "B",
    sectionId: "b-lodging",
    text: "얼리체크인/레이트체크아웃이 자주 필요한가요?",
    type: "single",
    options: o(["자주 필요", "가끔 필요", "거의 필요 없음"]),
  },
  {
    id: "B2-8",
    part: "B",
    sectionId: "b-lodging",
    text: "보유한 숙박 멤버십이 있나요?",
    type: "multi",
    allowCustom: true,
    options: o(["메리어트 본보이", "힐튼 아너스", "IHG 원", "아코르", "없음"]),
  },
  {
    id: "B2-9",
    part: "B",
    sectionId: "b-lodging",
    text: "평소 1박에 보통 쓰는 금액은?",
    type: "single",
    options: o(["5만원 이하", "5~10만원", "10~20만원", "20~40만원", "40만원 이상"]),
  },
  {
    id: "B2-10",
    part: "B",
    sectionId: "b-lodging",
    text: "숙소에서 가장 중요한 한 가지는?",
    type: "single",
    required: true,
    options: o(["위치", "가격", "청결도", "분위기/인테리어", "부대시설"]),
  },

  // B-3 신체·접근성·건강 (6)
  {
    id: "B3-1",
    part: "B",
    sectionId: "b-health",
    text: "이동 시 보조기구를 사용하나요?",
    type: "single",
    required: true,
    allowCustom: true,
    helpText: "더 안전하고 편안한 동선을 추천하기 위한 항목이에요. 언제든 삭제할 수 있어요.",
    options: o(["사용 안 함", "휠체어"]),
  },
  {
    id: "B3-2",
    part: "B",
    sectionId: "b-health",
    text: "현재 임신 중이거나 영유아를 동반하나요?",
    type: "single",
    options: o(["해당 없음", "임신 중", "영유아 동반"]),
  },
  {
    id: "B3-3",
    part: "B",
    sectionId: "b-health",
    text: "여행 중 고려해야 할 지병·주의사항이 있나요?",
    type: "text",
    helpText: "비공개로 저장되며 추천 안전성에만 활용됩니다.",
  },
  {
    id: "B3-4",
    part: "B",
    sectionId: "b-health",
    text: "평소 체력 수준은? (많이 걷거나 계단이 많아도 괜찮은지)",
    type: "scale",
    points: 5,
    lowLabel: "낮음",
    highLabel: "높음",
  },
  {
    id: "B3-5",
    part: "B",
    sectionId: "b-health",
    text: "차멀미·뱃멀미가 있나요?",
    type: "single",
    options: o(["있음", "없음"]),
  },
  {
    id: "B3-6",
    part: "B",
    sectionId: "b-health",
    text: "반려동물을 기르고 있나요?",
    type: "single",
    options: o(["기르지 않음", "기르지만 여행엔 안 데려감", "기르고 자주 함께 여행함"]),
  },

  // B-4 동행 기본 성향 (4)
  {
    id: "B4-1",
    part: "B",
    sectionId: "b-companion",
    text: "평소 가장 자주 함께 여행하는 대상은?",
    type: "single",
    required: true,
    options: o(["혼자", "연인", "친구", "가족(아이 동반)", "부모님(시니어 동반)", "반려동물"]),
  },
  {
    id: "B4-2",
    part: "B",
    sectionId: "b-companion",
    text: "아이와 함께하는 여행 경험이 있다면, 주로 어떤 연령대인가요?",
    type: "multi",
    allowCustom: true,
    options: o(["영유아(0~3세)", "유아동(4~7세)", "초등(8~13세)", "청소년(14~19세)"]),
  },
  {
    id: "B4-3",
    part: "B",
    sectionId: "b-companion",
    text: "부모님·시니어를 모시고 다닐 때 특별히 신경 쓰는 게 있나요?",
    type: "text",
  },
  {
    id: "B4-4",
    part: "B",
    sectionId: "b-companion",
    text: "반려동물 동반 여행을 자주 하는 편인가요?",
    type: "single",
    options: o(["자주 함", "가끔 함", "안 함"]),
  },

  // B-5 이동·로지스틱 (5)
  {
    id: "B5-1",
    part: "B",
    sectionId: "b-logistics",
    text: "여행 중 선호하는 이동수단은?",
    type: "multi",
    options: o(["도보", "대중교통", "렌터카(직접운전)", "택시/차량호출", "투어버스"]),
  },
  {
    id: "B5-2",
    part: "B",
    sectionId: "b-logistics",
    text: "장거리 이동 시 직항을 선호하나요?",
    type: "single",
    options: o(["직항 필수", "경유 상관없음"]),
  },
  {
    id: "B5-3",
    part: "B",
    sectionId: "b-logistics",
    text: "시차·장거리 이동 피로에 민감한 편인가요?",
    type: "scale",
    points: 5,
    lowLabel: "전혀 아님",
    highLabel: "매우 민감",
  },
  {
    id: "B5-4",
    part: "B",
    sectionId: "b-logistics",
    text: "외국어로 소통하는 데 자신감이 있나요?",
    type: "scale",
    points: 5,
    lowLabel: "자신 없음",
    highLabel: "매우 자신 있음",
  },
  {
    id: "B5-5",
    part: "B",
    sectionId: "b-logistics",
    text: "주로 다녀봤거나 관심 있는 지역권은?",
    type: "multi",
    options: o(["동아시아", "동남아", "유럽", "북미", "중남미", "중동", "아프리카", "오세아니아", "국내"]),
  },

  // B-6 예산·소비 (3)
  {
    id: "B6-1",
    part: "B",
    sectionId: "b-budget",
    text: "여행 중 가장 아끼지 않는 지출 항목은?",
    type: "single",
    required: true,
    options: o(["음식", "숙소", "쇼핑", "액티비티/체험", "교통"]),
  },
  {
    id: "B6-2",
    part: "B",
    sectionId: "b-budget",
    text: "반대로 가장 아끼는 편인 지출 항목은?",
    type: "single",
    options: o(["음식", "숙소", "쇼핑", "액티비티/체험", "교통"]),
  },
  {
    id: "B6-3",
    part: "B",
    sectionId: "b-budget",
    text: "여행 예산을 짤 때 방식은?",
    type: "single",
    options: o(["총액부터 정하고 항목별 배분", "항목별로 필요한 만큼", "그때그때 유동적"]),
  },

  // B-7 정보 습득 & 기록 (4)
  {
    id: "B7-1",
    part: "B",
    sectionId: "b-info",
    text: "여행지·맛집 정보를 주로 어디서 얻나요?",
    type: "multi",
    options: o(["인스타그램", "유튜브", "블로그", "지도앱 리뷰", "친구/지인 추천", "여행 커뮤니티", "방송/잡지"]),
  },
  {
    id: "B7-2",
    part: "B",
    sectionId: "b-info",
    text: "새로운 곳을 정할 때 가장 신뢰하는 정보는?",
    type: "single",
    options: o(["리뷰 개수", "평점", "지인 추천", "인플루언서 추천", "직접 검색한 사진"]),
  },
  {
    id: "B7-3",
    part: "B",
    sectionId: "b-info",
    text: "여행 중 사진·영상 기록을 얼마나 중요하게 여기나요?",
    type: "scale",
    points: 5,
    lowLabel: "전혀 중요하지 않음",
    highLabel: "매우 중요함",
  },
  {
    id: "B7-4",
    part: "B",
    sectionId: "b-info",
    text: "기념품·로컬 상품 쇼핑에 관심이 있나요?",
    type: "scale",
    points: 5,
    lowLabel: "전혀 없음",
    highLabel: "매우 많음",
  },
]

// ---------------------------------------------------------------------------
// Part C — 이번 여행 정보 (18문항)
// ---------------------------------------------------------------------------
const partC: Question[] = [
  // C-1 기본 정보
  {
    id: "C1-1",
    part: "C",
    sectionId: "c-basic",
    text: "이번 여행, 누구와 함께 하나요?",
    type: "multi",
    required: true,
    options: o(["혼자", "연인", "친구", "가족(아이 동반)", "부모님(시니어 동반)", "반려동물 동반"]),
  },
  {
    id: "C1-2",
    part: "C",
    sectionId: "c-basic",
    text: "총 동행 인원은 몇 명인가요? (본인 포함)",
    type: "number",
    required: true,
    min: 1,
  },
  {
    id: "C1-3",
    part: "C",
    sectionId: "c-basic",
    text: "이번 여행에 반려동물을 데려가나요?",
    type: "single",
    conditional: true,
    conditionNote: "반려동물을 기르고 자주 함께 여행하는 경우에만 노출",
    options: o(["예", "아니오"]),
  },
  {
    id: "C1-4",
    part: "C",
    sectionId: "c-basic",
    text: "이번 여행지는 어디인가요?",
    type: "text",
    required: true,
  },
  {
    id: "C1-5",
    part: "C",
    sectionId: "c-basic",
    text: "며칠 일정인가요?",
    type: "single",
    required: true,
    options: o(["당일치기", "1박2일", "2박3일", "3박4일", "4박5일 이상"]),
  },
  {
    id: "C1-6",
    part: "C",
    sectionId: "c-basic",
    text: "출발일을 알고 있다면 알려주세요",
    type: "date",
  },

  // C-2 예산
  {
    id: "C2-1",
    part: "C",
    sectionId: "c-budget",
    text: "이번 여행 전체 예산은 어느 정도로 생각하세요?",
    type: "single",
    options: o(["알뜰하게", "적당히", "넉넉하게", "프리미엄으로"]),
  },
  {
    id: "C2-2",
    part: "C",
    sectionId: "c-budget",
    text: "이번 여행 한 끼 식사 예산은?",
    type: "single",
    helpText: "평소 취향(Part B) 값이 기본으로 채워져요.",
    options: o(["1만원 이하", "1~2만원", "2~4만원", "4~7만원", "7만원 이상"]),
  },
  {
    id: "C2-3",
    part: "C",
    sectionId: "c-budget",
    text: "이번 여행 숙박 예산(1박)은?",
    type: "single",
    helpText: "평소 취향(Part B) 값이 기본으로 채워져요.",
    options: o(["5만원 이하", "5~10만원", "10~20만원", "20~40만원", "40만원 이상"]),
  },

  // C-3 목적·무드
  {
    id: "C3-1",
    part: "C",
    sectionId: "c-mood",
    text: "이번 여행의 주된 목적은?",
    type: "single",
    required: true,
    options: o(["순수 휴식", "기념일/이벤트", "액티비티/체험", "맛집 탐방", "업무 겸 여행", "가족 행사"]),
  },
  {
    id: "C3-2",
    part: "C",
    sectionId: "c-mood",
    text: "이번 여행에서 기대하는 분위기는? (최대 2개)",
    type: "multi",
    maxSelect: 2,
    options: o(["대도시/번화가", "자연/한적한 소도시", "바다/휴양지", "산/액티비티", "이국적인 낯선 문화권"]),
  },
  {
    id: "C3-3",
    part: "C",
    sectionId: "c-mood",
    text: "이번 여행에 특별한 의미가 있나요?",
    type: "single",
    options: o(["없음", "생일", "기념일(결혼기념일 등)", "승진/합격 등 축하", "힐링이 꼭 필요한 시기", "기타"]),
  },

  // C-4 컨디션
  {
    id: "C4-1",
    part: "C",
    sectionId: "c-condition",
    text: "요즘 컨디션이나 이번 여행에서 특별히 신경 써야 할 점이 있나요?",
    type: "text",
  },
  {
    id: "C4-2",
    part: "C",
    sectionId: "c-condition",
    text: "이번 여행에 동반하는 아이/시니어의 연령대는?",
    type: "multi",
    conditional: true,
    conditionNote: "동행자에 가족(아이) 또는 부모님(시니어) 포함 시만 노출",
    options: o(["영유아(0~3세)", "유아동(4~7세)", "초등(8~13세)", "청소년(14~19세)", "시니어(65세+)"]),
  },

  // C-5 축 오버라이드 (슬라이더)
  {
    id: "C5-1",
    part: "C",
    sectionId: "c-override",
    text: "이번 여행, 사람들과 어울리고 싶은 정도는?",
    type: "slider",
    overrideAxisId: "social",
    points: 5,
    lowLabel: "평소보다 조용히 쉬고 싶어요",
    highLabel: "평소보다 사람들과 어울리고 싶어요",
  },
  {
    id: "C5-2",
    part: "C",
    sectionId: "c-override",
    text: "이번 여행, 새로운 것에 도전하고 싶은 정도는?",
    type: "slider",
    overrideAxisId: "adventure",
    points: 5,
    lowLabel: "익숙하고 검증된 것 위주로",
    highLabel: "낯설고 새로운 것에 도전",
  },
  {
    id: "C5-3",
    part: "C",
    sectionId: "c-override",
    text: "이번 여행, 특별한 경험에 쓰고 싶은 정도는?",
    type: "slider",
    overrideAxisId: "experience",
    points: 5,
    lowLabel: "실속·가성비 위주로",
    highLabel: "특별한 경험에 아낌없이",
  },
  {
    id: "C5-4",
    part: "C",
    sectionId: "c-override",
    text: "이번 여행, 계획대로 움직이고 싶은 정도는?",
    type: "slider",
    overrideAxisId: "flow",
    points: 5,
    lowLabel: "계획대로 촘촘하게",
    highLabel: "발길 닿는 대로 즉흥적으로",
  },
]

// ---------------------------------------------------------------------------
// 16개 유형
// ---------------------------------------------------------------------------
const PERSONA_ROWS: [string, string, string, string, string[], string[]][] = [
  [
    "SAEF",
    "페스티벌 수달",
    "흥 따라, 사람 따라, 순간 따라",
    "사람들과 어울리며 새로운 경험을 즐기고, 계획보다 그날의 흐름에 몸을 맡기는 자유로운 여행자예요. 예상치 못한 만남과 즉흥적인 이벤트에서 최고의 순간을 발견합니다.",
    ["즉흥적인 분위기 메이커", "새로운 경험에 개방적", "사교성 만점"],
    ["로컬 페스티벌·야시장 일정을 미리 체크해 두세요.", "게스트하우스·파티형 숙소가 잘 맞아요.", "너무 빡빡한 일정보다 여백을 남겨두세요."],
  ],
  [
    "SAEJ",
    "갈라 플라밍고",
    "완벽하게 세팅된 특별한 순간을, 함께",
    "특별한 경험을 좋아하되 그것을 치밀하게 계획해 완성도 높게 즐기는 타입이에요. 함께하는 사람들과의 근사한 순간을 위해 준비를 아끼지 않습니다.",
    ["기획력 있는 리더", "특별한 경험 선호", "디테일에 강함"],
    ["인기 레스토랑·공연은 사전 예약이 필수예요.", "드레스코드가 있는 장소를 즐겨보세요.", "동행과 일정 공유 문서를 만들어두면 좋아요."],
  ],
  [
    "SAVF",
    "백패커 원숭이",
    "친구 따라 발길 닿는 대로, 실속있게",
    "친구들과 함께 정처 없이 떠돌며 가성비 있게 여행을 즐기는 타입이에요. 비싸지 않아도 즐거운 순간을 만드는 데 능합니다.",
    ["적응력이 뛰어남", "가성비 감각", "동행과의 케미"],
    ["도미토리·게스트하우스로 경비를 아껴보세요.", "현지 교통패스를 적극 활용하세요.", "즉흥 여행일수록 안전 정보는 꼭 챙기세요."],
  ],
  [
    "SAVJ",
    "플래너 꿀벌",
    "무리와 함께, 알뜰하고 야무지게",
    "무리와 함께하되 예산과 일정을 야무지게 관리하는 계획형 여행자예요. 알뜰하면서도 놓치는 것 없이 알찬 여행을 만듭니다.",
    ["꼼꼼한 예산 관리", "일정 최적화", "그룹 조율 능력"],
    ["공동 경비 정산 앱을 활용하세요.", "단체 할인·패스를 미리 알아보세요.", "예약 마감일을 캘린더로 관리하세요."],
  ],
  [
    "SCEF",
    "VIP 사자",
    "익숙한 사람들과 여유롭게, 근사하게",
    "익숙하고 검증된 것을 선호하면서도 근사한 경험에 아낌없이 투자하는 타입이에요. 가까운 사람들과 여유로운 프리미엄 여행을 즐깁니다.",
    ["품격 있는 취향", "여유로운 페이스", "신뢰 기반 관계"],
    ["단골처럼 즐길 수 있는 호텔 멤버십을 활용하세요.", "검증된 파인다이닝을 예약하세요.", "무리한 이동보다 한 곳에 머무는 여행을 추천해요."],
  ],
  [
    "SCEJ",
    "볼룸 백조",
    "격식 있게 준비된, 근사한 모임",
    "격식과 완성도를 중시하며 근사한 모임을 완벽하게 준비하는 타입이에요. 클래식하고 우아한 경험에서 만족을 느낍니다.",
    ["우아한 격식", "철저한 준비", "클래식 취향"],
    ["드레스코드·에티켓을 미리 확인하세요.", "정통 코스 요리를 경험해보세요.", "일정에 여유 있는 휴식 시간을 넣으세요."],
  ],
  [
    "SCVF",
    "동네 참새",
    "아는 사람들과 부담 없이, 즉흥적으로",
    "익숙한 사람들과 부담 없이, 큰 지출 없이 즉흥적으로 즐기는 타입이에요. 가까운 곳에서도 소소한 행복을 잘 찾습니다.",
    ["소탈한 즐거움", "부담 없는 소비", "친근한 분위기"],
    ["근교 당일치기 여행을 즐겨보세요.", "로컬 맛집·시장을 탐방하세요.", "무리한 계획 없이 가볍게 떠나세요."],
  ],
  [
    "SCVJ",
    "패밀리 펭귄",
    "다 같이, 알뜰하게, 꼼꼼하게",
    "가족·친구와 다 같이, 알뜰하고 꼼꼼하게 챙기는 안정 지향형 여행자예요. 모두가 편안한 여행을 만드는 데 진심입니다.",
    ["세심한 배려", "안정적인 계획", "알뜰함"],
    ["가족 친화 숙소·시설을 확인하세요.", "이동 동선을 최소화하세요.", "비상 연락처·보험을 챙기세요."],
  ],
  [
    "PAEF",
    "노마드 여우",
    "혼자, 자유롭게, 특별하게",
    "혼자만의 시간을 즐기며 자유롭고 특별한 경험을 좇는 타입이에요. 계획에 얽매이지 않고 나만의 리듬으로 여행합니다.",
    ["독립적", "특별함 추구", "자유로운 영혼"],
    ["1인 여행 친화 도시를 골라보세요.", "현지 원데이 클래스에 참여해보세요.", "숙소는 위치와 분위기를 우선하세요."],
  ],
  [
    "PAEJ",
    "탐험가 매",
    "혼자, 치밀하게, 깊이 있게",
    "혼자서 깊이 있게 파고들며 치밀하게 준비하는 탐구형 여행자예요. 한 곳을 제대로 경험하는 데서 만족을 얻습니다.",
    ["깊이 있는 탐구", "치밀한 계획", "집중력"],
    ["테마가 있는 심화 여행을 계획하세요.", "박물관·유적은 사전 학습 후 방문하세요.", "가이드 투어로 깊이를 더하세요."],
  ],
  [
    "PAVF",
    "로드 낙타",
    "혼자, 정처없이, 실속 있게",
    "혼자 정처 없이 떠돌면서도 실속을 챙기는 자유로운 방랑형이에요. 길 위에서의 우연을 즐깁니다.",
    ["강한 자립심", "실속 감각", "유연함"],
    ["장기 여행이면 거점 도시를 정하세요.", "현지 교통패스로 비용을 아끼세요.", "짐은 최대한 가볍게 꾸리세요."],
  ],
  [
    "PAVJ",
    "딜헌터 다람쥐",
    "혼자, 알뜰살뜰, 치밀하게",
    "혼자서 알뜰살뜰, 치밀하게 최적의 딜을 찾아내는 계획형 실속 여행자예요. 같은 경험을 더 저렴하게 즐기는 데 능합니다.",
    ["딜 헌팅 능력", "치밀한 계획", "예산 최적화"],
    ["항공·숙소 가격 알림을 설정하세요.", "비수기·특가 타이밍을 노리세요.", "리워드·마일리지를 적극 모으세요."],
  ],
  [
    "PCEF",
    "힐링 판다",
    "나만 아는 곳에서, 여유롭게",
    "나만 아는 조용한 곳에서 여유롭게 재충전하는 힐링형 여행자예요. 특별하지만 번잡하지 않은 쉼을 선호합니다.",
    ["여유로운 힐링", "조용한 취향", "재충전 능력"],
    ["한적한 소도시·자연을 골라보세요.", "스파·온천으로 몸을 풀어보세요.", "일정을 비워 충분히 쉬세요."],
  ],
  [
    "PCEJ",
    "료칸 거북이",
    "혼자, 완벽하게 준비된 프리미엄 휴식",
    "혼자만의 완벽하게 준비된 프리미엄 휴식을 즐기는 타입이에요. 검증된 고급 경험에서 편안함을 느��니다.",
    ["프리미엄 취향", "완벽한 준비", "차분함"],
    ["료칸·리조트는 일찍 예약하세요.", "룸서비스·프라이빗 시설을 활용하세요.", "동선을 최소화한 정적인 일정을 짜세요."],
  ],
  [
    "PCVF",
    "호캉스 코알라",
    "혼자, 부담 없이, 늘어져서",
    "혼자 부담 없이 늘어져 쉬는 것을 최고로 여기는 편안함 추구형이에요. 멀리 가지 않아도 푹 쉬면 만족합니다.",
    ["완벽한 휴식", "부담 없는 소비", "느긋함"],
    ["가성비 좋은 호캉스를 즐겨보세요.", "숙소 부대시설을 최대한 활용하세요.", "무리한 관광 대신 늦잠을 허용하세요."],
  ],
  [
    "PCVJ",
    "체크리스트 비버",
    "혼자, 완벽 계획, 검증된 곳만",
    "혼자서 완벽한 계획을 세우고 검증된 곳만 골라 가는 안정 지향형 여행자예요. 실패 없는 여행을 추구합니다.",
    ["철저한 계획", "리스크 관리", "검증된 선택"],
    ["후기가 많은 검증된 장소를 고르세요.", "체크리스트로 준비물을 관리하세요.", "여행 보험·환불 정책을 확인하세요."],
  ],
]

const PERSONAS = PERSONA_ROWS.map(([code, name, tag, description, strengths, tips]) => {
  const details = PERSONA_DETAILS[code]
  return {
    code,
    name,
    tag,
    description: details?.description ?? description,
    strengths: details?.strengths ?? strengths,
    tips: details?.tips ?? tips,
    companions: details?.companions,
    catchphrases: details?.catchphrases,
    motto: details?.motto,
    docSlug: details?.docSlug,
  }
})

// ---------------------------------------------------------------------------
// 기본 설문 전체
// ---------------------------------------------------------------------------
export const DEFAULT_SURVEY: Survey = {
  version: "v2.0",
  title: "TRAVEL ANIMAL 16",
  subtitle: "나는 어떤 여행 동물일까?",
  axes: [
    {
      id: "social",
      name: "사교성",
      field: "social_score",
      lowLabel: "프라이빗",
      highLabel: "소셜",
      lowCode: "P",
      highCode: "S",
      colorVar: "--chart-1",
    },
    {
      id: "adventure",
      name: "취향모험도",
      field: "adventure_score",
      lowLabel: "클래식",
      highLabel: "어드벤처",
      lowCode: "C",
      highCode: "A",
      colorVar: "--chart-2",
    },
    {
      id: "experience",
      name: "가치관",
      field: "experience_score",
      lowLabel: "가성비",
      highLabel: "경험",
      lowCode: "V",
      highCode: "E",
      colorVar: "--chart-3",
    },
    {
      id: "flow",
      name: "계획성",
      field: "flow_score",
      lowLabel: "플랜",
      highLabel: "플로우",
      lowCode: "J",
      highCode: "F",
      colorVar: "--chart-4",
    },
  ],
  sections: [
    { id: "a-personality", part: "A", title: "성격", description: "당신의 성향을 다양한 각도에서 살펴봐요." },
    { id: "a-travel", part: "A", title: "여행 스타일", description: "여행지에서의 나는 어떤 모습일까요?" },
    { id: "a-food", part: "A", title: "음식 스타일", description: "먹는 것에 대한 태도를 알아봐요." },
    { id: "a-lodging", part: "A", title: "숙소 스타일", description: "어디서 쉴 때 가장 나다운가요?" },
    { id: "b-food", part: "B", title: "음식 프로필", description: "구체적인 식성과 제약을 알려주세요." },
    { id: "b-lodging", part: "B", title: "숙소 프로필", description: "숙소에서 꼭 필요한 것들을 알려주세요." },
    { id: "b-health", part: "B", title: "신체·접근성·건강", description: "더 안전한 추천을 위한 항목이에요. (비공개)" },
    { id: "b-companion", part: "B", title: "동행 기본 성향", description: "평소 누구와 여행하나요?" },
    { id: "b-logistics", part: "B", title: "이동·로지스틱", description: "이동과 소통에 대한 취향이에요." },
    { id: "b-budget", part: "B", title: "예산·소비", description: "돈을 쓰는 방식을 알려주세요." },
    { id: "b-info", part: "B", title: "정보 습득 & 기록", description: "정보를 얻고 기록하는 습관이에요." },
    { id: "c-basic", part: "C", title: "이번 여행 기본 정보", description: "이번 한 번의 여행에 대해 알려주세요." },
    { id: "c-budget", part: "C", title: "이번 여행 예산", description: "평소 값을 기본으로 채워뒀어요." },
    { id: "c-mood", part: "C", title: "이번 여행 목적·무드", description: "이번 여행에서 기대하는 것은?" },
    { id: "c-condition", part: "C", title: "이번 여행 컨디션", description: "특별히 신경 쓸 점이 있나요?" },
    { id: "c-override", part: "C", title: "이번만 다르게", description: "평소 성향을 이번 여행에만 잠깐 조정해요. (선택)" },
  ],
  questions: [
    ...makeLikert(partAPersonality, "a-personality"),
    ...makeLikert(partATravel, "a-travel"),
    ...makeLikert(partAFood, "a-food"),
    ...makeLikert(partALodging, "a-lodging"),
    ...partB,
    ...partC,
  ],
  personas: PERSONAS,
  weightFeatures: [
    { id: "taste_ratio", label: "맛 (taste)", base: 0.2, k: 0, axisId: "" },
    { id: "mood_ratio", label: "분위기 (mood)", base: 0.1, k: 0.15, axisId: "experience" },
    { id: "price_ratio", label: "가격 (price)", base: 0.1, k: -0.15, axisId: "experience" },
    { id: "novelty_score", label: "새로움 (novelty)", base: 0.1, k: 0.2, axisId: "adventure" },
    { id: "menu_match", label: "메뉴 매칭 (menu match)", base: 0.2, k: 0, axisId: "" },
    { id: "popularity_norm", label: "인기도 (popularity)", base: 0.15, k: 0.1, axisId: "social" },
    { id: "buzz_ratio", label: "화제성 (buzz)", base: 0.05, k: 0.1, axisId: "social" },
    { id: "reservation_bonus", label: "예약 보너스", base: 0.15, k: -0.15, axisId: "flow" },
  ],
  scoring: {
    axisThreshold: 0.5,
    neutralScore: 0.5,
    weightPivot: 0.5,
    weightClampMin: 0,
  },
}
