CREATE TABLE IF NOT EXISTS "RequestLog" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
  "chatId" uuid NOT NULL REFERENCES "Chat"("id"),
  "userMessageId" uuid REFERENCES "Message_v2"("id"),
  "assistantMessageId" uuid REFERENCES "Message_v2"("id"),
  "userId" uuid NOT NULL REFERENCES "User"("id"),
  "createdAt" timestamp NOT NULL,
  "intent" varchar(32),
  "intentLabel" text,
  "needsCanvas" boolean NOT NULL DEFAULT false,
  "hasRawJson" boolean NOT NULL DEFAULT false,
  "rawJson" text,
  "hasNodeData" boolean NOT NULL DEFAULT false,
  "nodeData" json,
  "hasErrorLog" boolean NOT NULL DEFAULT false,
  "errorLog" text,
  "model" varchar(64),
  "selectedVisibility" varchar(16),
  "priorMessageCount" integer,
  "responseLength" integer,
  "hasStructuredPayload" boolean NOT NULL DEFAULT false,
  "structuredPayloads" json,
  "latencyMs" integer,
  "userAgent" text,
  "ipAddress" varchar(45)
);
